
all: pthread_model_test
	@echo "##########compile over!##########"
	
pthread_model_test:
	gcc -o pthread_model_test pthread_model.c pthread_model_test.c -lpthread -g 

	
clean:
	rm -rf *.o pthread_model_test
	
